### ISSUE TITLE
Cannot up with docker-compose

### ISSUE THREAD

**Issue by rodush** [vovimayhem/docker-compose-rails-dev-example#1]
I did everything as described, and I saw that `sidekiq` bundle was installed, unfortunately:

> Cannot start container 1b3cc6c98867b301be1c1af54e9a8c7f780b8f86230913351a9b1b1a387dc19e: [8] System error: exec: "sidekiq": executable file not found in $PATH

**Comment by vovimayhem** [comment]
Oh my! Thanks for your interest!

This project was a personal demo I used for teaching my team about Docker some time ago. Frankly I forgot I had this repo.

Curiously enough, I've got [another repo](https://github.com/vovimayhem/rails-docker-demo) into which I was throwing some lines a couple of minutes ago for the exact same reason (Be sure to check the [feature/forum-functionality](https://github.com/vovimayhem/rails-docker-demo/tree/feature/forum-functionality)...)

There you can find an updated rails app, and an updated docker-compose example, with plenty of comments for you to check out. Feel free to ask any question up there.

**Comment by vovimayhem** [comment]
PS: I configured the docker-compose.yml file to use a dotenv file which is not committed into the repo, make sure you copy the dev.env.example file I have over there

**Comment by rodush** [comment]
okay, thanks!

**Comment by vovimayhem** [comment]
This repo is very old, and a lot of stuff changed in docker-world since then. Nonetheless, I updated this repo to reflect how I get things done today.

Be sure to check the updated [README]( https://github.com/vovimayhem/docker-compose-rails-dev-example/blob/master/README.md)
