### ISSUE TITLE
Cannot run docker compose

### ISSUE THREAD

**Issue by shaharrubin** [vovimayhem/docker-compose-rails-dev-example#2]
Hi,
Thank you for your upload.
When I installing the docker (through the installation script you provided), it throws some warnings and errors:
Creating example_postgres_1
ERROR: Invalid volume spec "db/postgres-setup.sql/docker-entrypoint-initdb.d/setup.sql": volumeabs: Invalid volume destination path: 'db/postgres-setup.sql/docker-entrypoint-initdb.d/setup.sql' mount path must be absolute.
Waiting 20 seconds for the postgres container to finish initializing (Hit ENTER to continue right away) - Continuing with app database setup:
WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

Creating example_postgres_1
ERROR: Invalid volume spec "db/postgres-setup.sql/docker-entrypoint-initdb.d/setup.sql": volumeabs: Invalid volume destination path: 'db/postgres-setup.sql/docker-entrypoint-initdb.d/setup.sql' mount path must be absolute.
WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

Stopping example_redis_1 ... done

I tried to run it with sudo, it says:
WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

WARNING: There is a boolean value in the 'environment', 'labels', or 'extra_hosts' field of a service.
These sections only support string values.
Please add quotes to any boolean values to make them strings (eg, 'True', 'false', 'yes', 'N', 'on', 'Off').
This warning will become an error in a future release. 

ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

the docker machine is running. Similar warnings are rising when I try to run the compose

**Comment by vovimayhem** [comment]
Sorry for not responding in time... actually this repo is very old, and a lot of stuff changed in docker-world since then. Nonetheless, I updated this repo to reflect how I get things done today.

Be sure to check the updated [README]( https://github.com/vovimayhem/docker-compose-rails-dev-example/blob/master/README.md)

**Comment by rubyconvict** [comment]
Try: "./db/postgres-setup.sql:/docker-entrypoint-initdb.d/setup.sql". The colon was missing.
